// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo3PAAwY3xz7Nr7GTcOanTcim534-12ko',
    appId: '1:331365450222:web:6cff2a096b907620444eff',
    messagingSenderId: '331365450222',
    projectId: 'meditrack-498d8',
    authDomain: 'meditrack-498d8.firebaseapp.com',
    storageBucket: 'meditrack-498d8.firebasestorage.app',
    measurementId: 'G-Y6P8FJT46P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDTumOW9aHjdB_WopkMv3lzZqOUIncVQ8',
    appId: '1:331365450222:android:89d77900dcc5b842444eff',
    messagingSenderId: '331365450222',
    projectId: 'meditrack-498d8',
    storageBucket: 'meditrack-498d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzGaonF3Qoud0DEES7rIPhVk7L4JvBnm8',
    appId: '1:331365450222:ios:624649d68221bbea444eff',
    messagingSenderId: '331365450222',
    projectId: 'meditrack-498d8',
    storageBucket: 'meditrack-498d8.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzGaonF3Qoud0DEES7rIPhVk7L4JvBnm8',
    appId: '1:331365450222:ios:624649d68221bbea444eff',
    messagingSenderId: '331365450222',
    projectId: 'meditrack-498d8',
    storageBucket: 'meditrack-498d8.firebasestorage.app',
    iosBundleId: 'com.example.meditrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo3PAAwY3xz7Nr7GTcOanTcim534-12ko',
    appId: '1:331365450222:web:94a7139c1d571b5b444eff',
    messagingSenderId: '331365450222',
    projectId: 'meditrack-498d8',
    authDomain: 'meditrack-498d8.firebaseapp.com',
    storageBucket: 'meditrack-498d8.firebasestorage.app',
    measurementId: 'G-LCHZKJJSG3',
  );

}